/**
 * Risk Engine Enums and Data Types
 */

export const RISK_FLAGS = {
  SEASONAL_DEMAND: 'SEASONAL_DEMAND',
  SINGLE_BUYER_DEPENDENCY: 'SINGLE_BUYER_DEPENDENCY',
  SUPPLY_CHAIN_FRAGILITY: 'SUPPLY_CHAIN_FRAGILITY',
  HIGH_COMPETITION_DENSITY: 'HIGH_COMPETITION_DENSITY'
}

export const RISK_SEVERITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
}

export const RISK_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
}

export const STRESS_SCENARIOS = {
  OPTIMISTIC: 'OPTIMISTIC',
  EXPECTED: 'EXPECTED',
  CONSERVATIVE: 'CONSERVATIVE',
  SEVERE: 'SEVERE'
}

export const STRESS_VERDICTS = {
  COMFORTABLE: 'COMFORTABLE',
  MANAGEABLE: 'MANAGEABLE',
  TIGHT: 'TIGHT',
  HIGH_RISK: 'HIGH_RISK'
}

export const DATA_SOURCES = {
  CATEGORY_RULE: 'CATEGORY_RULE',
  MARKET_DATA: 'MARKET_DATA',
  USER_REPORTED: 'USER_REPORTED',
  FINANCIAL_ENGINE: 'FINANCIAL_ENGINE',
  STRESS_TEST: 'STRESS_TEST'
}
