export const RULE_VERSION = '2026-08'
export const financialRules = {
  NBCFDC_INDIVIDUAL: { schemeId: 'NBCFDC_INDIVIDUAL', schemeVersion: RULE_VERSION, effectiveFrom: '2026-08-01', financing: { corporationShare: 0.85, beneficiaryMargin: 0.15 }, loanLimit: { maximum: 2500000 }, interest: { type: 'TIERED', tiers: [{ maximum: 125000, corporationRate: 4, beneficiaryRate: 7 }, { maximum: 2500000, corporationRate: 5, beneficiaryRate: 8 }] }, repayment: { tenureYears: 7, moratoriumMonths: 3 }, rebate: { rate: 1, condition: 'timely_repayment', calculation: 'subject_to_applicable_terms' } },
  NBCFDC_GROUP: { schemeId: 'NBCFDC_GROUP', schemeVersion: RULE_VERSION, effectiveFrom: '2026-08-01', financing: { corporationShare: 0.9, beneficiaryMargin: 0.1 }, loanLimit: { maximum: 1500000, perBeneficiary: 125000 }, interest: { type: 'FIXED', beneficiaryRate: 6 }, repayment: { tenureYears: 3, moratoriumMonths: 3 } },
  NBCFDC_EDUCATION: { schemeId: 'NBCFDC_EDUCATION', schemeVersion: RULE_VERSION, effectiveFrom: '2026-08-01', financing: { corporationShare: 1, beneficiaryMargin: 0 }, loanLimit: { maximum: 1500000 }, interest: { type: 'FIXED', beneficiaryRate: 8 }, repayment: { tenureYears: 10, moratoriumMonths: 60 } },
  NSFDC_MICRO_FINANCE: { schemeId: 'NSFDC_MICRO_FINANCE', schemeVersion: RULE_VERSION, effectiveFrom: '2026-08-01', financing: { corporationShare: 0.9, beneficiaryMargin: 0.1 }, loanLimit: { maximum: 125000 }, interest: { type: 'FIXED', beneficiaryRate: 6.5 }, repayment: { tenureYears: 3, moratoriumMinMonths: 3, moratoriumMaxMonths: 4 } },
  NSFDC_AAJEEVIKA: { schemeId: 'NSFDC_AAJEEVIKA', schemeVersion: RULE_VERSION, effectiveFrom: '2026-08-01', financing: { corporationShare: 0.9, beneficiaryMargin: 0.1 }, loanLimit: { maximum: 125000 }, interest: { type: 'FIXED', beneficiaryRate: 15 }, repayment: { tenureYears: 3 } },
  NSFDC_TERM_LOAN: { schemeId: 'NSFDC_TERM_LOAN', schemeVersion: RULE_VERSION, effectiveFrom: '2026-08-01', financing: { corporationShare: 0.9, beneficiaryMargin: 0.1 }, loanLimit: { maximum: 5000000 }, interest: { type: 'FIXED', beneficiaryRate: 8 }, repayment: { tenureYears: 7, moratoriumMonths: 6, specialMoratorium: { projectTypes: ['plantation', 'construction'], months: 12 } } },
  NSFDC_UDYAM_NIDHI: { schemeId: 'NSFDC_UDYAM_NIDHI', schemeVersion: RULE_VERSION, effectiveFrom: '2026-08-01', financing: { corporationShare: 0.9, beneficiaryMargin: 0.1 }, loanLimit: { maximum: 450000 }, interest: { type: 'RANGE', minRate: 13, maxRate: 15 }, repayment: { tenureYears: 5 } },
  NSFDC_EDUCATION: { schemeId: 'NSFDC_EDUCATION', schemeVersion: RULE_VERSION, effectiveFrom: '2026-08-01', financing: { corporationShare: 0.9, beneficiaryMargin: 0.1 }, loanLimit: { maximum: 4000000 }, interest: { type: 'FIXED', beneficiaryRate: 6.5 }, repayment: { tenureYears: 12 } },
  NSKFDC_MAHILA_SAMRIDHI: { schemeId: 'NSKFDC_MAHILA_SAMRIDHI', schemeVersion: RULE_VERSION, effectiveFrom: '2026-08-01', financing: { corporationShare: 1, beneficiaryMargin: 0 }, loanLimit: { maximum: 100000 }, interest: { type: 'FIXED', beneficiaryRate: 6 }, repayment: { tenureYears: 3 } },
  NSKFDC_MAHILA_ADHIKARITA: { schemeId: 'NSKFDC_MAHILA_ADHIKARITA', schemeVersion: RULE_VERSION, effectiveFrom: '2026-08-01', financing: { corporationShare: 1, beneficiaryMargin: 0 }, loanLimit: { maximum: 200000 }, interest: { type: 'FIXED', beneficiaryRate: 7 }, repayment: { tenureYears: 5 } },
  NSKFDC_MICRO_CREDIT: { schemeId: 'NSKFDC_MICRO_CREDIT', schemeVersion: RULE_VERSION, effectiveFrom: '2026-08-01', financing: { corporationShare: 0.9, beneficiaryMargin: 0.1 }, loanLimit: { maximum: 100000 }, interest: { type: 'FIXED', beneficiaryRate: 7 }, repayment: { tenureYears: 3, implementationMonths: 4, moratoriumMonths: 6 } },
  NSKFDC_GENERAL_TERM_LOAN: { schemeId: 'NSKFDC_GENERAL_TERM_LOAN', schemeVersion: RULE_VERSION, effectiveFrom: '2026-08-01', financing: { corporationShare: 1, beneficiaryMargin: 0 }, loanLimit: { maximum: 1500000 }, interest: { type: 'RANGE', minRate: 8, maxRate: 9 }, repayment: { tenureYears: 10 } },
  NSKFDC_EDUCATION: { schemeId: 'NSKFDC_EDUCATION', schemeVersion: RULE_VERSION, effectiveFrom: '2026-08-01', financing: { corporationShare: 1, beneficiaryMargin: 0 }, loanLimit: { maximum: (input) => String(input.education?.india_or_abroad || input.education?.country).toLowerCase() === 'abroad' ? 2000000 : 1000000 }, interest: { type: 'RANGE', minRate: 6, maxRate: 7 }, repayment: { tenureYears: 10 } },
  NSKFDC_PAY_USE_TOILET: { schemeId: 'NSKFDC_PAY_USE_TOILET', schemeVersion: RULE_VERSION, effectiveFrom: '2026-08-01', financing: { corporationShare: 1, beneficiaryMargin: 0 }, loanLimit: { maximum: 2500000 }, interest: { type: 'FIXED', beneficiaryRate: 8 }, repayment: { tenureYears: 10 } },
  NSKFDC_SANITARY_MART: { schemeId: 'NSKFDC_SANITARY_MART', schemeVersion: RULE_VERSION, effectiveFrom: '2026-08-01', financing: { corporationShare: 1, beneficiaryMargin: 0 }, loanLimit: { maximum: 1500000 }, interest: { type: 'FIXED', beneficiaryRate: 7 }, repayment: { tenureYears: 10 } },
  NSKFDC_GREEN_BUSINESS: { schemeId: 'NSKFDC_GREEN_BUSINESS', schemeVersion: RULE_VERSION, effectiveFrom: '2026-08-01', financing: { corporationShare: 1, beneficiaryMargin: 0 }, loanLimit: { maximum: 3000000 }, interest: { type: 'RANGE', minRate: 6, maxRate: 8 }, repayment: { tenureYears: 10 } },
  NSKFDC_SWACHHTA_UDYAMI: { schemeId: 'NSKFDC_SWACHHTA_UDYAMI', schemeVersion: RULE_VERSION, effectiveFrom: '2026-08-01', financing: { corporationShare: 1, beneficiaryMargin: 0 }, loanLimit: { maximum: (input) => String(input.nskfdc?.applicant_type).toLowerCase() === 'group' ? 5000000 : 1500000 }, interest: { type: 'FIXED', beneficiaryRate: 6 }, repayment: { tenureYears: 7 } }
}

export function getFinancialRules(schemeId) { return financialRules[schemeId] }
