import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import StepIndicator from '../components/StepIndicator'
import { useAssessment } from '../hooks/useAssessment'
import { submitFinancialAssessment } from '../services/assessmentApi'

const corporations = [['NBCFDC', 'NBCFDC', 'National Backward Classes Finance & Development Corporation'], ['NSFDC', 'NSFDC', 'National Scheduled Castes Finance & Development Corporation'], ['NSKFDC', 'NSKFDC', 'National Safai Karamcharis Finance & Development Corporation']]
const purposeOptions = { NBCFDC: [['business', 'Business / Income Generation'], ['education', 'Education'], ['group', 'Group / SHG']], NSFDC: [['micro_finance', 'Micro Finance'], ['small_business', 'Business / Income Generation'], ['education', 'Education']], NSKFDC: [['small_business', 'Small Business'], ['micro_credit', 'Micro Credit'], ['education', 'Education'], ['sanitation_enterprise', 'Sanitation'], ['green_business', 'Green Business'], ['other', 'Other']] }
const businessTypes = [['grocery_shop', 'Grocery Shop'], ['salon', 'Salon'], ['tailoring', 'Tailoring'], ['restaurant', 'Restaurant'], ['dairy', 'Dairy'], ['poultry', 'Poultry'], ['manufacturing', 'Manufacturing'], ['workshop', 'Workshop'], ['retail', 'Retail'], ['service_business', 'Service Business'], ['transport', 'Transport'], ['other', 'Other']]
const states = ['Andhra Pradesh', 'Bihar', 'Delhi', 'Gujarat', 'Karnataka', 'Madhya Pradesh', 'Maharashtra', 'Odisha', 'Rajasthan', 'Tamil Nadu', 'Uttar Pradesh', 'West Bengal']
const occupations = ['Student', 'Farmer', 'Self-employed', 'Business owner', 'Salaried', 'Daily wage worker', 'Unemployed', 'Other']
const ranges = [['below_1_lakh', 'Below INR 1 lakh', 50000], ['1_to_5_lakh', 'INR 1-5 lakh', 250000], ['5_to_10_lakh', 'INR 5-10 lakh', 750000], ['10_to_25_lakh', 'INR 10-25 lakh', 1750000], ['above_25_lakh', 'INR 25 lakh+', 2500000]]
const money = (value) => `INR ${Number(value || 0).toLocaleString('en-IN')}`
const numeric = (value) => value === '' ? '' : Math.max(0, Number(value) || 0)

function Field({ label, value, onChange, type = 'text', options, required = false, placeholder }) {
  return <label className="block text-sm font-semibold text-inkSoft">{label}{required && <span className="text-saffron"> *</span>}{options ? <select value={value ?? ''} onChange={(event) => onChange(event.target.value)} className="assessment-input mt-2"><option value="">Select an option</option>{options.map(([id, text]) => <option key={id} value={id}>{text}</option>)}</select> : <input value={value ?? ''} onChange={(event) => onChange(type === 'number' ? numeric(event.target.value) : event.target.value)} type={type} min={type === 'number' ? 0 : undefined} placeholder={placeholder} className="assessment-input mt-2" />}</label>
}
function Choices({ options, value, onChange, columns = 'md:grid-cols-3' }) { return <div className={`grid gap-4 ${columns}`} role="radiogroup">{options.map(([id, label, description]) => <button type="button" role="radio" aria-checked={value === id} key={id} onClick={() => onChange(id)} className={`choice-card text-left ${value === id ? 'choice-card-selected' : ''}`}><span className="flex justify-between gap-3"><strong className="font-display text-lg">{label}</strong><span className={`choice-dot ${value === id ? 'choice-dot-selected' : ''}`}>{value === id ? '✓' : ''}</span></span>{description && <span className="block mt-3 text-sm text-inkSoft">{description}</span>}</button>)}</div> }
function ReviewRows({ rows }) { return <dl className="grid sm:grid-cols-2 gap-x-8 gap-y-2">{rows.filter(([, value]) => value !== '' && value !== undefined && value !== null).map(([label, value]) => <div className="flex justify-between gap-4 text-sm" key={label}><dt className="capitalize text-inkSoft">{label.replaceAll('_', ' ')}</dt><dd className="font-semibold text-right">{value}</dd></div>)}</dl> }

export default function SimpleAssessment() {
  const { assessment, setAssessment, setAssessmentResult } = useAssessment()
  const navigate = useNavigate()
  const [step, setStep] = useState(1)
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const [apiError, setApiError] = useState('')
  const profile = assessment.profile || {}
  const requirement = assessment.requirement || {}
  const business = assessment.business || {}
  const financial = assessment.financial || {}
  const businessPurpose = ['business', 'small_business', 'micro_finance', 'micro_credit', 'large_business', 'women_business', 'sanitation_enterprise', 'green_business'].includes(requirement.purpose)
  const update = (section, field, value) => setAssessment((current) => ({ ...current, [section]: { ...(current[section] || {}), [field]: value } }))
  const validate = () => {
    let message = ''
    if (step === 1 && !assessment.corporation) message = 'Select one organization.'
    if (step === 2 && (!profile.age || !profile.gender || !profile.category || profile.annual_family_income === '' || !profile.state || !profile.district || !profile.occupation)) message = 'Complete all required profile fields.'
    if (step === 3 && (!requirement.purpose || (assessment.corporation === 'NSKFDC' && !requirement.beneficiary_type))) message = 'Select the assistance you need.'
    if (step === 3 && businessPurpose && (!business.businessType || (business.businessType === 'other' && !business.businessDescription))) message = 'Tell us what business you are planning.'
    if (step === 4 && (!financial.requestedAmount || financial.requestedAmount <= 0 || financial.ownContribution === '' || financial.otherFunding === '')) message = 'Enter your approximate requirement and funding sources.'
    setError(message)
    return !message
  }
  const next = () => { if (validate()) setStep((value) => Math.min(5, value + 1)) }
  const payload = () => ({ corporation: assessment.corporation, profile: { ...profile, age: Number(profile.age), annual_family_income: Number(profile.annual_family_income) }, requirement: { purpose: requirement.purpose, beneficiary_type: requirement.beneficiary_type }, business: businessPurpose ? { businessType: business.businessType, businessDescription: business.businessDescription } : undefined, financial: { requestedAmount: Number(financial.requestedAmount), ownContribution: Number(financial.ownContribution), otherFunding: Number(financial.otherFunding) } })
  const submit = async () => { if (!validate()) return; setLoading(true); setApiError(''); try { const response = await submitFinancialAssessment(payload()); const result = response.data || response; setAssessmentResult(result); navigate(`/scheme-results/${result.scheme?.schemeId || result.recommendation?.scheme_code || 'unavailable'}`) } catch (submissionError) { setApiError(submissionError.message); setLoading(false) } }
  const selectedRange = (id) => update('financial', 'requestedAmount', ranges.find(([rangeId]) => rangeId === id)?.[2] || '')
  const approximate = financial.requestedAmount ? money(financial.requestedAmount) : 'Not entered'

  return <div className="assessment-page grid-bg-fine"><div className="max-w-5xl mx-auto px-6 lg:px-10 py-10 md:py-16"><div className="flex items-center justify-between mb-12"><Link to="/" className="text-sm font-semibold text-inkSoft hover:text-saffron">← Back</Link><span className="font-mono text-xs text-inkSoft">SECURE · NO LOGIN REQUIRED</span></div><div className="max-w-4xl mx-auto"><p className="eyebrow">Start Assessment</p><div className="flex flex-col md:flex-row md:items-end justify-between gap-3 mb-8"><div><h1 className="font-display text-4xl md:text-5xl font-semibold mb-3">Find your financing path.</h1><p className="text-inkSoft">Five simple steps. Clearer answers before you borrow.</p></div><span className="font-mono text-sm text-inkSoft">Step {step} of 5</span></div><StepIndicator totalSteps={5} currentStep={step} /><section className="assessment-panel mt-12" aria-live="polite">
    {step === 1 && <><h2 className="assessment-title">Which organization applies to you?</h2><p className="text-inkSoft mb-8">Choose the corporation category you want to explore. The backend determines the applicable scheme.</p><Choices options={corporations} value={assessment.corporation} onChange={(value) => setAssessment((current) => ({ ...current, corporation: value, requirement: { purpose: '', beneficiary_type: '' } }))} /></>}
    {step === 2 && <><h2 className="assessment-title">About you</h2><p className="text-inkSoft mb-8">Now tell us the profile details needed for scheme discovery.</p><div className="grid md:grid-cols-2 gap-6"><Field label="Age" type="number" value={profile.age} onChange={(value) => update('profile', 'age', value)} required /><Field label="Gender" value={profile.gender} onChange={(value) => update('profile', 'gender', value)} options={['male', 'female', 'other', 'prefer_not_to_say'].map((value) => [value, value.replaceAll('_', ' ')])} required /><Field label="Social / beneficiary category" value={profile.category} onChange={(value) => update('profile', 'category', value)} options={['SC', 'OBC', 'SAFAI_KARAMCHARI', 'DEPENDANT', 'OTHER'].map((value) => [value, value])} required /><Field label="Annual family income (INR)" type="number" value={profile.annual_family_income} onChange={(value) => update('profile', 'annual_family_income', value)} required /><Field label="State" value={profile.state} onChange={(value) => update('profile', 'state', value)} options={states.map((value) => [value, value])} required /><Field label="District" value={profile.district} onChange={(value) => update('profile', 'district', value)} placeholder="Enter your district" required /><Field label="Occupation" value={profile.occupation} onChange={(value) => update('profile', 'occupation', value)} options={occupations.map((value) => [value, value])} required /><Field label="Certificate status" value={profile.caste_certificate === true ? 'true' : profile.caste_certificate === false ? 'false' : ''} onChange={(value) => update('profile', 'caste_certificate', value === 'true' ? true : value === 'false' ? false : null)} options={[['true', 'Yes'], ['false', 'No'], ['unknown', 'Not sure']]} /></div></>}
    {step === 3 && <><h2 className="assessment-title">Your requirement</h2><p className="text-inkSoft mb-8">What do you need financial assistance for?</p>{assessment.corporation === 'NSKFDC' && <div className="mb-8"><h3 className="font-display text-2xl font-semibold mb-4">Which best describes you?</h3><Choices options={['Safai Karamchari', 'Wastepicker', 'Manual Scavenger', 'Eligible Dependant'].map((value) => [value, value])} value={requirement.beneficiary_type} onChange={(value) => update('requirement', 'beneficiary_type', value)} columns="md:grid-cols-2" /></div>}<Choices options={(purposeOptions[assessment.corporation] || []).map(([id, label]) => [id, label])} value={requirement.purpose} onChange={(value) => update('requirement', 'purpose', value)} columns="md:grid-cols-2" /></>}
    {step === 3 && businessPurpose && <><h2 className="assessment-title">What are you planning?</h2><p className="text-inkSoft mb-8">Business type is for context only. We will not guess its cost.</p><Choices options={businessTypes} value={business.businessType} onChange={(value) => update('business', 'businessType', value)} columns="md:grid-cols-3" />{business.businessType === 'other' && <Field label="Describe your business" value={business.businessDescription} onChange={(value) => update('business', 'businessDescription', value)} required placeholder="For example, mobile repair service" />}</>}
    {step === 3 && !businessPurpose && <><h2 className="assessment-title">A focused requirement</h2><p className="text-inkSoft">No detailed business questions are needed for this assistance type.</p></>}
    {step === 4 && <><h2 className="assessment-title">Basic financial requirement</h2><p className="text-inkSoft mb-8">Use an approximate project requirement. The backend calculates the financing available under the selected scheme.</p><div className="space-y-8"><div><h3 className="font-display text-2xl font-semibold mb-4">Approximate requirement</h3><Choices options={ranges.map(([id, label]) => [id, label])} value={ranges.find(([id, , amount]) => amount === financial.requestedAmount)?.[0]} onChange={selectedRange} columns="md:grid-cols-2" /><div className="mt-5"><Field label="Or enter an approximate amount (INR)" type="number" value={financial.requestedAmount} onChange={(value) => update('financial', 'requestedAmount', value)} required placeholder="800000" /></div></div><div className="grid md:grid-cols-2 gap-6"><Field label="How much can you contribute? (INR)" type="number" value={financial.ownContribution} onChange={(value) => update('financial', 'ownContribution', value)} required /><Field label="Other funding (INR)" type="number" value={financial.otherFunding} onChange={(value) => update('financial', 'otherFunding', value)} required /></div><div className="result-section"><p className="result-note">YOUR INPUT</p><p className="font-display text-2xl font-semibold mt-2">Approximate project requirement: {approximate}</p><p className="text-sm text-inkSoft mt-2">This is an input, not a promise of exact business cost.</p></div></div></>}
    {step === 5 && <><h2 className="assessment-title">Review & calculate</h2><p className="text-inkSoft mb-8">Review the facts you provided. Final financing numbers come from the backend.</p><div className="space-y-6"><div><h3 className="font-display text-xl font-semibold mb-3">About you <button type="button" className="text-sm text-saffronDeep ml-3" onClick={() => setStep(1)}>Edit</button></h3><ReviewRows rows={Object.entries(profile)} /></div><div><h3 className="font-display text-xl font-semibold mb-3">Route <button type="button" className="text-sm text-saffronDeep ml-3" onClick={() => setStep(2)}>Edit</button></h3><ReviewRows rows={[["corporation", assessment.corporation], ["purpose", requirement.purpose], ["beneficiary_type", requirement.beneficiary_type], ["business_type", business.businessType], ["business_description", business.businessDescription]]} /></div><div><h3 className="font-display text-xl font-semibold mb-3">Financial requirement <button type="button" className="text-sm text-saffronDeep ml-3" onClick={() => setStep(4)}>Edit</button></h3><ReviewRows rows={[["approximate requirement", money(financial.requestedAmount)], ["own contribution", money(financial.ownContribution)], ["other funding", money(financial.otherFunding)]]} /></div></div></>}
    {error && <p className="mt-6 text-sm text-maroon" role="alert">{error}</p>}{apiError && <div className="mt-6 border-2 border-maroon/30 bg-maroon/5 p-4 rounded-xl text-maroon" role="alert"><strong>We couldn&apos;t calculate your funding options.</strong><p className="text-sm mt-1">{apiError} Your answers are still saved.</p></div>}<div className="flex items-center justify-between gap-4 mt-12 pt-8 border-t border-line"><button type="button" onClick={() => { setError(''); setStep((value) => Math.max(1, value - 1)) }} disabled={step === 1 || loading} className="btn-ghost px-5 py-3 font-bold disabled:opacity-30">← Back</button>{step < 5 ? <button type="button" onClick={next} className="btn-primary text-beige font-bold px-7 py-3 rounded-full">Continue →</button> : <button type="button" onClick={submit} disabled={loading} className="btn-primary text-beige font-bold px-7 py-3 rounded-full disabled:opacity-60">{loading ? 'Analyzing your assessment...' : 'Calculate My Options →'}</button>}</div></section></div></div></div>
}
