export const ENGINE_VERSION = '1.0.0'
export const CORPORATIONS = ['NBCFDC', 'NSFDC', 'NSKFDC']
export const STATUS = { ELIGIBLE: 'ELIGIBLE', NOT_ELIGIBLE: 'NOT_ELIGIBLE', NEEDS_VERIFICATION: 'NEEDS_VERIFICATION' }
